const ETAPPEN = [
    {
        "user": "fritzcrone",
        "nr": 6,
        "titel": "Ehrwald - Scharnitz",
        "startpunkt": "Ehrwald",
        "endpunkt": "Scharnitz",
        "gebirgszug": "Wettersteingebirge",
        "km": "40,0",
        "bergauf": 990,
        "bergab": 1020,
        "hoechster_punkt": 1590,
        "tiefster_punkt": 900,
        "fahrzeit": "4:00",
        "grad": "mittelschwer",
        "intro": "Rund 1.000 Höhenmeter gilt es auf dieser 40 Kilometer langen Etappe zu überwinden – außer, Sie legen einen Teil der Strecke (400 Höhenmeter) mit der Ehrwalder Almbahn zurück. Belohnt wird diese als mittelschwer eingestufte Etappe mit einer atemberaubenden Kulisse: Die Zugspitze präsentiert sich als stete Begleiterin, ehe Sie am Tor zum Naturpark Karwendel stehen.",
        "streckenverlauf": "Zunächst radelt man leicht ansteigend bis zur Talstation der Ehrwalder Almbahn. Von hier geht es immer aufwärts auf der Route Nr. 813 bis zur Ehrwalder Alm (1,5h ab Ehrwald). Alternativ kann man die Gondelbahn benutzen. Von der Ehrwalder Alm geht es weiter am Hauptweg aufwärts, in zwei Kehren zum höchsten Punkt auf 1.600m Seehöhe. Kurz danach an der markanten Abzweigung zur Seeben Alm hält man sich links Richtung Leutasch (551). Bei einem Abstecher zur Tillfussalm oder Gaistalalm wird man mit einem eindrucksvollen Blick auf die steil abfallenden Nordwände der Mieminger Kette belohnt. Weiter geht es auf dem Hauptweg durch das Gaistal, vorbei an der Mautstelle, bis in den Leutascher Ortsteil Klamm. Hier radelt man über die Brücke nach Obern und orientiert sich am „Hotel Bergland“. Nun geht es über die nächste Straße Richtung Leutasch Oberweidach (2h ab der Ehrwalder Alm). Der Weg führt bald in den Wald und wieder überquert man eine Straße, danach fährt man links in einen Waldweg. Ab hier folgt man immer den Schildern „539 Mooserweg Seepromenade“ bzw. „Leutasch Weidach“. Nach Passieren des Weidachsees erreicht man die Hauptstraße. Dieser folgt man etwa 350 Meter und zweigt dann gleich wieder rechts ab „541 Katzenkopf- Fluder“. Nun folgt ein Anstieg im Wald über 200 Höhenmeter und eine Abfahrt durchs Fludertal bis zur Straße. Dieser folgt man kurz in nördlicher Richtung bis man auf die Straße nach Scharnitz abzweigt. Kurz bevor man die Bundesstraße erreicht, zweigt man links in die Wiesen bei Giessenbach ab und radelt die letzten Kilometer zum Etappenziel nach Scharnitz (1,5h ab Leutasch Weidach).",
        "weblink": "https://www.wildganz.com/radfernweg-aut/bike-trail-tirol-etappe-6"
    },
    {
        "user": "webmapping",
        "nr": 7,
        "titel": "Scharnitz - Achensee",
        "startpunkt": "Scharnitz",
        "endpunkt": "Maurach am Achensee",
        "gebirgszug": "Karwendel",
        "km": "61,5",
        "bergauf": 1850,
        "bergab": 1880,
        "hoechster_punkt": 1800,
        "tiefster_punkt": 960,
        "fahrzeit": "6:00",
        "grad": "schwer",
        "intro": "Diese als schwierig eingestufte Tour verlangt Können und Kondition. Mit 60 Kilometern Länge und 1.850 zu überwindenden Höhenmetern zählt sie zu einer der längsten und schwierigsten Etappen. Sie führt Sie durch die kontrastreiche Landschaft des Karwendels, das Ihnen mit schroffen Felsen, satten Wiesen und grünen Wäldern das breite Spektrum der Bergwelt offenbart.",
        "streckenverlauf": "Nach dem Start radelt man zunächst einen Kilometer taleinwärts, ehe man links auf die Forststraße zum Karwendelhaus abzweigt. Ohne Abzweigungen fährt man nun durch das Karwendeltal bis zum Karwendelhaus. Nur ein kurzer Anstieg ist es bis zum Hochalmsattel. Nach einer Abfahrt erreicht man den Kleinen Ahornboden und fährt nun auf gut ausgebauten Forststraßen durchs Johannestal Richtung Hinterriß. Im Rißtal angekommen radelt man taleinwärts bis zur Abzweigung auf das Plumsjoch. Nun geht es noch einmal gute 500 Höhenmeter zur Plumsjochhütte hinauf. Nach der Einkehr folgt eine technisch schwierige Abfahrt (Singletrail Plumsjoch oder Schiebestrecke) ins Gerntal und auf einer asphaltierten Straße weiter nach Pertisau. Nach der Ortsdurchfahrt radelt man direkt neben dem Achensee auf einem Radweg zum Etappenziel beim Parkplatz in Maurach- Buchau.",
        "weblink": "https://www.wildganz.com/radfernweg-aut/bike-trail-tirol-etappe-7"
    },
    {
        "user": "lujehle",
        "nr": 8,
        "titel": "Achensee - Kaiserhaus",
        "startpunkt": "Maurach am Achensee",
        "endpunkt": "Kaiserhaus in Brandenberg",
        "gebirgszug": "Brandenberger Alpen (Rofan)",
        "km": "56,0",
        "bergauf": 1460,
        "bergab": 1660,
        "hoechster_punkt": 1490,
        "tiefster_punkt": 700,
        "fahrzeit": "5:00",
        "grad": "schwer",
        "intro": "Beschauliche Passagen, kraftvolle Anstiege und flotte Abfahrten kennzeichnen diese als schwierig eingestufte Route, bei der Sie rund 1.500 Höhenmeter überwinden. Die Etappe führt am Gumpen entlang durch waldreiches Gebiet. Nach einer langen Abfahrt von der Gufferthütte erreichen Sie das Brandenbergtal, das schon seit dem Mittelalter für seinen Holzreichtum und als feudales Jagdgebiet bekannt ist. Die Kaiserhütte am Einstieg zur Kaiserklamm ist ein 500 Jahre altes Forsthaus, in dem schon Kaiser Franz Joseph I. einkehrte.",
        "streckenverlauf": "Man folgt zu Beginn den Radwegweisern der Via Bavarica Tyrolensis (29) und fährt am Ostufer des Achensees entlang nach Achenkirch (45min ab Maurach). Etwa 500 Meter nördlich des Sees zweigt man rechts über eine Brücke ab, um gleich wieder rechts neben einer Doppelgarage in einen Feldweg einzufahren. Nach weiteren 150 Metern unterquert man die Achenseebundesstraße und fährt parallel dazu 400 Meter in nördlicher Richtung bis zur Abzweigung „Köglalm“. Den Radwegweisern (Nr. 461, bis zur Alm auch 402) folgt man nun über die Köglalm aufs Kögljoch und dann wieder abwärts, vorbei an der Schönjochalm bis nach Steinberg am Rofan (2,5h ab Achenkirch). Von hier geht es auf der Hauptstraße etwa 2,5 km in nordwestlicher Richtung bis zur Abzweigung des „Alten Steinbergwegs“ (461, 465). Auf diesem guten Forstweg bleibt man etwa 3 Kilometer, bis man rechts abzweigt (464, 465). Bei Erreichen der Straße fährt man kurz links und nach etwa 150 Metern geht es rechts vorbei am großen Parkplatz zum Forstweg auf die Gufferthütte (464, 465). Diesem folgt man bis zur Hütte (2h ab Steinberg). Nach der Einkehr fährt man die letzten 200 Meter zurück und folgt dann den Wegweisern Richtung Kaiserhaus (464, 465). Nach der Brücke über die Brandenberger Ache zweigt man rechts ab und fährt im Tal bis zum Kaiserhaus (344, 465; 1h 15min ab Gufferthütte).",
        "weblink": "https://www.wildganz.com/radfernweg-aut/bike-trail-tirol-etappe-8"
    },
   
]